name: Update Marketplace JSON

on:
  push:
    branches:
      - main

jobs:
  update-marketplace-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Update marketplace.json
        run: node .github/scripts/update-marketplace.js

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update marketplace.json"
          branch: main
